2016-06-24 Specified 9090 port for spring boot app. Fixed truncated words in quotation pop. Removed springboot reference in mars-sim-core. Removed external library nimrod 1.2d and fixed classpath.
1. Adjusted the parameters of a quotation popup based on 1366x768 laptop screen size, instead of 1920x1080.

2. Commmented out the springboot maven artifact and codes in mars-sim-core in order to avoid conflict with the springboot maven artifact in mars-sim-ui.

3. Added application.properties file in the root directory of /main/resource and specified "server.port=9090"

4. Removed external library nimrod 1.2d in mars-sim-ui and gave rise to maven error and fixed some .classpath files in eclipse.

5. Uploaded mars-sim-network-3.1.0-SNAPSHOT.jar as mars-sim-core depends on it.

------------------------------------------------------------------------------------------------------------------
Note: 
------------------------------------------------------------------------------------------------------------------

When running SpringAppLeaf.java in eclipse, it's possible that port 8080 has been used by another windows application

The stacktrace will show the following:

2016-06-24 21:44:29.800 ERROR 10552 --- [           main] o.a.coyote.http11.Http11NioProtocol      : Failed to start end point associated with ProtocolHandler ["http-nio-8080"]

java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_92]

.
.
.

In this case, the workaround is to specify another port for use, such as using port 9090 in application.properties and type in "http://localhost:9090/" in browser.