Move Master branch to become Java 9/10 compatible
r4268
2018-05-24

Note 1 : as of this build, mars-sim's codebase has now been officially
switched to using jdk 9 or above (incompatible with jdk 8 from now on)
as agreed upon in issue https://github.com/mars-sim/mars-sim/issues/37

Note 2 : still working on the java 9 compatibility issue with
WebLookAndFeel package in mars-sim-ui's pom.xml that will give the
following error when running mars-sim :
[AWT-EventQueue-0] ERROR com.alee.utils.ProprietaryUtils -
java.lang.NoSuchFieldException: AA_TEXT_PROPERTY_KEY

Note 3 : the maven build is a success (target for Java 9).
However, the size of the jar increased from 91MB to 117MB.

# CHANGES
1. Bump up controlsfx from 8.40.14 to 9.0.0
2. Bump up jfoenix from 8.0.4 to 9.0.4
3. Update module-info.java in mars-sim-main and mars-sim-ui.

# FIXES
1. Fix javafx.fxml.LoadException and java.lang.ClassNotFoundException
   at dashboard.fxml
   - Switch to Java 9 compatible version of fontawesome in pom.xml
   and include MaterialDesignIconView and FontAwesomeIconView
   -- fontawesomefx-commons 9.1.2
   -- fontawesomefx-fontawesome 4.7.0-9.1.2
   -- fontawesomefx-materialdesignfont 2.0.26-9.1.2
2. Fix maven compiling error of having com.sun.* Internal APIs :
   - Comment out all four classes in org.mars_sim.msp.ui.javafx.svg
     folder since they use
3. Fix SwingFXWebView.java by removing the use of Internal API.

# NEW
1. Add an issue ticket template in README.md. See issue
https://github.com/mars-sim/mars-sim/issues/63