Track O2, CO2. Modulate solarHeatGain. Misc fix
r4178
2017-10-10

# FIX 
1. Correct the NullPointerException due to the getSettlement() in 
   Malfunctionable. 
   - Change MalfunctionEvent to return entity.getSettlementName().
2. Fix the high temperature issue in Schiaparelli Point
   - Block the excessive sunlight from coming into the building if the 
     temperature of the building is 5 degrees higher than normal.
     - Add if conditions to modulate solarHeatGain calculation in 
       determineDeltaTemperature() in Heating.
3. Correct multiple drivers reportedly driving the same vehicle.
   - Modify mobilizeVehicle() in OperateVehicle to call clearTask() if 
     the driver gives way to another settler. This ensure that only one 
	 driver at a time during mission.
4. Attempting to fix the scenario :
> RescueSalvageVehicle : Denise Gregory is driving Sand Crawler to 
  rendezvous with Sand Crawler
> IllegalArgumentException: Rover cannot tow itself.
   - Relocate a block of codes to create reserveVehicle() which in turns
     call getAvailableVehicles() and isUsableVehicle() in 
     VehicleMission.
   - Modify isUsableVehicle() in RescueSalvageVehicle to filter out the 
     rescuing vehicle as the targetVehicle. (it will override 
	 isUsableVehicle() in VehicleMission.
Note that the first time reserveVehicle() is called in VehicleMission,
the selected vehicle list often contains the stranded vehicle. That's
why reserveVehicle() needs to be called the second time.
   
# NEW 
1. Add daily tracking of O2 generation, CO2 consumption in greenhouses
   - Add cumulative_o2, cumulative_co2 in Crop.
   - Add cropDailyO2Generated, cropDailyCO2Consumed, computeO2Generated,
     computeCO2Consumed(), computeCropO2Generated(), 
     computeCropCO2Consumed(), AddO2(), AddCO2(), AddO2Generated(), 
     AddCO2Consumed(), o2, co2 in Farming.
   - Add o2Cache, co2Cache, o2Label, co2Label, o2TF, co2TF for o2 and 
     co2 tracking in BuildingPanelFarming.
2. Incorporate O2 and CO2 calculation in calculateGasExchange() 
   in CompositionOfAir.
3. Add a new LocationTag class for more detailed location tracking and
   hopefully removing the use of the null 
   - Use getLocationName() in MalfunctionEvent.
   - Change getSettlement() to getLocationName()
4. Add LocationSituation.UNKNOWN and remove the use of the null if
   no LocationSituation fits the case.
5. Add setWaterRatio() and waterRatio in Person.
6. Add "Large Sabatier Processor" building for the Alpha Base template 
   in settlements.xml.
 
# CHANGE 
1. Cache the latitude and longitude strings in Coordinate
   - Add latCache, lonCache
   - Use it in getFormattedLongitudeString() and 
     getFormattedLongitudeString()  	
2. Modify cycleThermalControl() in Heating to allow for rapidly 
   increasing and decreasing temperature under new conditions.
3. Add margins in getEstimatedMissionCost() in TradeUtil.   
4. Report the vehicle or the building where a medical event takes place 
   rather than just the settlement. 
   - Change to return person.getLocationTag().getLocationName() 
     in MedicalEvent    
5. Sync up the drop-in x-locations and y-locations of the "ERV Base", 
   "Starting Base", "MD1 Nuclear Reactor" found in each template 
   settlements.xml and their corresponding resupply missions building 
   manifest list in resupplies.xml.