Update dependencies and expose more Java 9/10 incompatbilities
r4264
2018-05-17

Notes :
1. more code change will take place in the next few commits
in order to remove incompatbilities when running mars-sim
under Java 9/10/11 due to Java 9 modularization and JavaFX related
internal API change.

2. e.g. Exception in thread "JavaFX Application Thread"
java.lang.NoClassDefFoundError: com/sun/javafx/css/parser/CSSParser

This is caused by: java.lang.ClassNotFoundException:
com.sun.javafx.css.parser.CSSParser

# CHANGE
1. Update the following dependencies :
 - jfoenix from 1.11.1 to 8.0.4
 - tilesfx from 1.5.2 to 1.5.6
 - Medusa from 7.9 to 8.0
 - centerdevice-nsmenufx from 2.1.5 to 2.1.6
 - wellbehavedfx from 0.3 to 0.3.3
 - log4j-core from 2.9.1 to 2.11.0
 - from org.jcraft's jorbis 0.0.17 to
   com.googlecode.soundlibs's jorbis 0.0.17.4
 - flowless from 0.5.2 to 0.6.1
 - miglayout-javafx from 5.0 to 5.1
 - jfreechart-fx from 1.0.0 to 1.0.1
 - javafxsvg from 1.2.1 to 1.3.0