Fix weblookandfeel issue with Java 9
r4269
2018-05-24

# CHANGES
1. Rename two eclipse launcher
   - "MarsProject new.launch" to "MarsProject -new.launch"
   - "MarsProject.launch" to "MarsProject -load default.launch"

# FIXES
1. Resolve the following 2 errors, namely,
   a. [AWT-EventQueue-0] ERROR com.alee.utils.ProprietaryUtils -
java.lang.NoSuchFieldException: AA_TEXT_PROPERTY_KEY
   b. [AWT-EventQueue-0] ERROR com.alee.utils.LafUtils - Unable to
   initialize L&F for class name: com.alee.laf.WebLookAndFeel
   com.alee.managers.style.StyleException:
   StyleManager must be initialized

   via switching the following 2 weblookandfeel packages
   - weblaf-ui: from de.sciss v2.1.3
     to com.weblookandfeel v1.2.9-SNAPSHOT
   - weblaf-core: from de.sciss v2.1.3
     to com.weblookandfeel v1.2.9-SNAPSHOT

> Note : seehttps://github.com/mgarin/weblaf/issues/452

2. Switch from importing com.alee.managers.language.data.TooltipWay
   to com.alee.managers.tooltip.TooltipWay in various class.